export { default as AboutMe } from './AboutMe'
export { default as ContactMe } from './ContactMe'
export { default as Experience } from './Experience'
export { default as Home } from './Home'
export { default as Skills } from './Skills'
export { default as Certificates } from './Certificates'
export { default as Studies } from './Studies'